### ISSUE TITLE
Kubernetes pods considers requests value rather than limits values.

### ISSUE THREAD

**Issue by thapabishwa** [KimMachineGun/automemlimit#11]
I have deployed a k8s pod with both `automemlimit` and `automaxproc` and I have set the resources to the following:

```
resources:
  limits:
    cpu: 2
    memory: 4Gi

  requests:
     cpu: 1
     memory: 2Gi
```
`automemlimits` uses the request value rather than the limits values set on the k8s manifest. Is this expected behavior?

`automaxprocs` uses the limits value set on manifest rather than the request value. 

I was under the impression that `automemlimits` did the same thing for memory limits like `automaxprocs` did for cpu limits. 

Am I missing something here?
